services:
  - type: web
    name: agrisage
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: REDIS_URL
        sync: false
      - key: REDIS_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true